import { NonFinancialService } from "../types";

export const mockNonFinancialServices: NonFinancialService[] = [
  {
    id: "1",
    name: "Business Registration & Licensing",
    slug: "business-registration-licensing",
    description:
      "Complete business registration and licensing services to establish your company legally in the UAE with all required permits and documentation.",
    category: "Registration",
    industry: "All Industries",
    processingTime: "5-10 business days",
    cost: "AED 3,500",
    rating: 4.8,
    reviews: 234,
    isNew: true,
    features: [
      "Trade License Registration",
      "Commercial Registration",
      "Municipality Permits",
      "Immigration Services",
      "Bank Account Opening",
    ],
    provider: "Khalifa Business Services",
    eligibility: [
      "UAE resident or investor",
      "Valid Emirates ID",
      "Business plan documentation",
      "Minimum capital requirements",
    ],
    requirements: [
      "Passport copies",
      "Emirates ID",
      "Business plan",
      "NOC from sponsor (if applicable)",
    ],
    benefits: [
      "Legal business establishment",
      "Access to UAE banking",
      "Government contract eligibility",
      "Visa sponsorship capability",
    ],
    contact: {
      phone: "+971 2 123 4567",
      email: "registration@khalifafund.ae",
      address: "Business Services Center, Abu Dhabi",
    },
    createdAt: "2024-01-15T10:00:00Z",
    facetValues: [],
    customFields: {
      Industry: "All Industries",
      BusinessStage: "Startup",
      ProcessingTime: "5-10 business days",
      RegistrationValidity: "1 year renewable",
      Cost: 3500,
      Steps: "Application → Document Review → Registration → License Issuance",
      TermsOfService: "Standard business registration terms",
      RequiredDocuments: "Passport, Emirates ID, Business plan, NOC",
      RelatedServices: [
        { id: "2", name: "Legal Advisory", slug: "legal-advisory" },
        { id: "3", name: "Accounting Services", slug: "accounting-services" },
      ],
    },
  },
  {
    id: "2",
    name: "Legal Advisory & Compliance",
    slug: "legal-advisory-compliance",
    description:
      "Professional legal advisory services and regulatory compliance support to ensure your business operates within UAE legal framework.",
    category: "Legal",
    industry: "All Industries",
    processingTime: "1-3 business days",
    cost: "AED 1,500",
    rating: 4.9,
    reviews: 189,
    isNew: false,
    features: [
      "Legal Consultation",
      "Contract Review",
      "Compliance Auditing",
      "Regulatory Guidance",
      "Dispute Resolution",
    ],
    provider: "Khalifa Legal Services",
    eligibility: [
      "Registered UAE business",
      "Valid trade license",
      "Legal documentation needs",
    ],
    requirements: [
      "Business registration documents",
      "Current legal documents",
      "Specific legal query details",
    ],
    benefits: [
      "Legal compliance assurance",
      "Risk mitigation",
      "Professional guidance",
      "Dispute prevention",
    ],
    contact: {
      phone: "+971 2 234 5678",
      email: "legal@khalifafund.ae",
      address: "Legal Services Center, Dubai",
    },
    createdAt: "2024-01-10T14:30:00Z",
    facetValues: [],
    customFields: {
      Industry: "All Industries",
      BusinessStage: "All Stages",
      ProcessingTime: "1-3 business days",
      RegistrationValidity: "Ongoing support",
      Cost: 1500,
      Steps: "Consultation → Analysis → Advice → Implementation Support",
      TermsOfService: "Professional legal services terms",
      RequiredDocuments: "Business documents, legal query details",
      RelatedServices: [
        {
          id: "1",
          name: "Business Registration",
          slug: "business-registration-licensing",
        },
        { id: "4", name: "Compliance Services", slug: "compliance-services" },
      ],
    },
  },
  {
    id: "3",
    name: "Accounting & Financial Services",
    slug: "accounting-financial-services",
    description:
      "Comprehensive accounting and financial management services including bookkeeping, tax preparation, and financial reporting.",
    category: "Accounting",
    industry: "All Industries",
    processingTime: "2-5 business days",
    cost: "AED 2,500",
    rating: 4.7,
    reviews: 156,
    isNew: false,
    features: [
      "Monthly Bookkeeping",
      "Tax Preparation & Filing",
      "Financial Reporting",
      "Payroll Management",
      "VAT Registration & Filing",
    ],
    provider: "Khalifa Accounting Services",
    eligibility: [
      "UAE registered business",
      "Regular business transactions",
      "Financial record requirements",
    ],
    requirements: [
      "Business financial records",
      "Bank statements",
      "Transaction documentation",
      "Previous tax filings",
    ],
    benefits: [
      "Accurate financial records",
      "Tax compliance",
      "Financial insights",
      "Time savings",
    ],
    contact: {
      phone: "+971 2 345 6789",
      email: "accounting@khalifafund.ae",
      address: "Financial Services Center, Sharjah",
    },
    createdAt: "2024-01-20T09:15:00Z",
    facetValues: [],
    customFields: {
      Industry: "All Industries",
      BusinessStage: "Operational",
      ProcessingTime: "2-5 business days",
      RegistrationValidity: "Monthly/Annual contracts",
      Cost: 2500,
      Steps: "Setup → Data Collection → Processing → Reporting → Filing",
      TermsOfService: "Professional accounting services terms",
      RequiredDocuments: "Financial records, bank statements, transaction docs",
    },
  },
];
